### ISSUE TITLE
organization landing page

### ISSUE THREAD

**Issue by scottyhq** [uwhackweek/hackweeks-as-a-service#4]
Currently going to https://uwhackweek.github.io results in a 404 error

But the 'Hackweek Guidebook' is available at:
https://uwhackweek.github.io/hackweeks-as-a-service/intro.html

It would be nice to have a landing page at the root URL. There are many options for this, such as 

1. another jupyterbook. Maybe just a simple gallery style page that links to other hackweeks:
https://executablebooks.org/en/latest/gallery.html 

2. a splashy landing page like we've done for past events:
https://geohackweek.github.io 

thoughts on URL organization @lsetiawan @aaarendt ?

**Comment by scottyhq** [comment]
as a bare minimum I just created https://github.com/uwhackweek/uwhackweek.github.io which automatically renders whatever you have in README.md directly in HTML at https://uwhackweek.github.io. Pretty convenient, but not very flashy !

**Comment by aaarendt** [comment]
I agree this is needed @scottyhq. Thanks for getting something temporary set up. I can see the value in a simple page that has a gallery of all of our past offerings. Helps people to get a feel for our overall portfolio. 

But maybe we put a flashy landing page in front of everything? If so what should we use? I've now done Gatsby and Jekyll. Any suggestions? I could try to get something started.

**Comment by scottyhq** [comment]
> But maybe we put a flashy landing page in front of everything? If so what should we use? I've now done Gatsby and Jekyll. Any suggestions? I could try to get something started. 

I don't have any experience with these sorts of websites, but @lsetiawan pointed to https://html5up.net/ (geohackweek used the 'spectral' theme) and https://startbootstrap.com/?showPro=false&showVue=false&showAngular=false

**Comment by lsetiawan** [comment]
I suggest staying with either JS Static Site generator such as Gatsby, or maybe like Python Pelican. I'm not super excited about jekyll anymore since it's in Ruby... The links I sent are simply html templates, that can be used by any static site generator. I think maybe since both @aaarendt and I can navigate through Gatsby, maybe we should use that. I think if we can set it up so it generate pages from markdown, it would be good. Here is a good place for gatsby starters: https://codebushi.com/gatsby-starters-and-themes/

**Comment by jomey** [comment]
This seems all resolved or no longer applicable.

We have the guidbook now published under guidebook.hackweek.io and more general Hackweek content under the eScience Wordpress.
